### ISSUE TITLE
ごあいさつ

### ISSUE THREAD

**Issue by hitobb** [niufy/Test#1]
hitobbですこんにちわ。
Javaのリポジトリ作成されているので簡単かもしれませんが、
Readme.meの更新をお願いします。

完成しましたら、こちらにコメントを返してみてください！

それでは！

**Comment by niufy** [comment]
Readmeを書き直し、commitしました。
これで良いでしょうか？

**Comment by hitobb** [comment]
OK、確認しました。

**Comment by hitobb** [comment]
質問者が自主的にケースオープンした場合は、再オープンが可能です。

**Comment by hitobb** [comment]
再度、クローズします。
