### ISSUE TITLE
他リポジトリからのフォークテスト

### ISSUE THREAD

**Issue by hitobb** [niufy/Test#4]
おつかれさまです。

https://github.com/BitzenyCoreDevelopers/bitzeny

こちらを、自分自身の領域へフォークしてみてください。
クリックするボタンの配置が微妙にわかりにくいので、ご注意くださいねｗ

よろしくお願いいたします。

**Comment by niufy** [comment]
いつもお世話になります。
だいぶ時間を空けてしまい、すみまえん。
さきほど、forkしました。
確かにちょっと分かりづらいですね。
分散型の開発はgitの大きな特徴のひとつなのだから、もっと目立つ感じでも良いですよね。

**Comment by hitobb** [comment]
はい、確認しました。
では次のミッション。

https://github.com/niufy/bitzeny

を、削除してください。
怖いでしょうけど、いつか通る道ですw
さぁ、チャレンジ！

**Comment by niufy** [comment]
ただいまリポジトリを削除しました。
結構ドキドキしますね。

**Comment by hitobb** [comment]
確認しました。
では本件、クローズします。

次ありますよwww

**Comment by hitobb** [comment]
次の課題は、明日以降に発表します。お疲れ様でした。

**Comment by niufy** [comment]
ありがとうございました。
